// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/cosmos/cosmos-sdk/x/genaccounts/internal/types
package genaccounts

import (
	"github.com/dfinance/dnode/x/genaccounts/internal/types"
)

const (
	ModuleName = types.ModuleName
)

var (
	// functions aliases
	GetGenesisStateFromAppState = types.GetGenesisStateFromAppState
	SetGenesisStateInAppState   = types.SetGenesisStateInAppState
	ValidateGenesis             = types.ValidateGenesis

	// variable aliases
	ModuleCdc = types.ModuleCdc
)

type (
	GenesisState = types.GenesisState
)
